export const HIGHLIGHT_LABELS: Record<string, string> = {
  supermarkets: 'Supermarkets',
  highStreet: 'High street',
  pubsBars: 'Pubs & bars',
  restaurantsCafes: 'Dining out',
  parksGreenSpaces: 'Green spaces',
  gymsLeisure: 'Gyms & leisure',
  healthcare: 'Healthcare',
  librariesCulture: 'Culture',
  schools: 'Good schools',
  publicTransport: 'Public transport',
  trainStation: 'Train access',
  greenSpaces: 'Green spaces',
  peaceAndQuiet: 'Peace & quiet',
  broadband: 'Fast broadband',
  commute: 'Short commute',
  familyProximity: 'Near family',
  socialScene: 'Social scene',
};
